version: 0.2

phases:
  install:
    commands:
      - npm install # Ensures all dependencies including devDependencies are installed
  build:
    commands:
      - npm run build
      - npm run test
artifacts:
  files:
    - dist-server/**/*
